name: Count LOC

on:
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get install cloc

      - name: Clone all repos and count LOC
        run: |
          USERNAME=tanishkhub
          mkdir repos
          cd repos

          for repo in $(curl -s https://api.github.com/users/$USERNAME/repos | grep clone_url | cut -d '"' -f 4); do
            git clone --depth 1 $repo
          done

          cloc .
